#!/bin/sh
# Rename the `swe` placeholder to `shimmer` (ADR 0011). Run from the repo root, on any
# branch: it rewrites tracked files in place and is safe to run twice. Use it to rebase a
# branch that predates the rename: run it on your branch, then `cargo build` to refresh
# Cargo.lock, then resolve whatever is left by hand.
#
# Whole patterns only, so words that merely contain "swe" ("answer") are untouched:
#   SWE_       -> SHIMMER_     env vars ($SWE_HOME, SWE_SOCKET, ...)
#   swe_ swe-  -> shimmer_ shimmer-   crates, imports, /tmp/swe-mock.sock
#   swe        -> shimmer      the whole word: the command, binary, paths (/swe/)
#
# Skipped: Cargo.lock (regenerated by cargo), docs/decisions/ (ADRs keep their history; see
# ADR 0011), and this script.
set -eu

git ls-files -z -- . ':!Cargo.lock' ':!docs/decisions/' ':!.dev/rename-to-shimmer.sh' |
    xargs -0 grep -l -I -E 'swe|SWE' 2>/dev/null |
    while IFS= read -r f; do
        perl -pi -e '
            s/\bCARGO_BIN_EXE_swe\b/CARGO_BIN_EXE_shimmer/g;
            s/\bSWE_/SHIMMER_/g;
            s/\bswe([_-])/shimmer$1/g;
            s/\bswe\b/shimmer/g;
        ' "$f"
    done

echo "Renamed. Now run: cargo build (refreshes Cargo.lock), then"
echo "  git grep -n -w -i swe   # should list only docs/decisions/ and .dev/rename-to-shimmer.sh"
